GAME_CREATED = 0
GAME_READY = 1
GAME_PLAYING = 2
GAME_FINISH = 3
EDITABLE_STATUS = [GAME_CREATED, GAME_READY]
GAME_STATUS = {GAME_CREATED: 'Created', GAME_READY: 'Ready to play', GAME_PLAYING: 'Playing', GAME_FINISH: 'Finished'}
GAME_TITLE_MIN_MAX_LEN = {'min': 5, 'max': 150}
TIME_LIMIT_OPTION = {'option': [10, 20, 30, 40, 50, 60], 'selected': 30}
ANSWER_COUNT_OPTION = {'option': [2, 3, 4, 5, 6], 'selected': 4}
POINT_PER_QUESTION_OPTION = {'option': [1, 5, 10, 50, 100], 'selected': 10}
TOP_RANK_OPTION = {'option': [1, 3, 4, 5, 10], 'selected': 3}
