# Generated by Django 2.2.11 on 2020-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.TextField()),
                ('game_setting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_question_id', models.BigIntegerField()),
                ('question', models.TextField()),
                ('true_answer_number', models.IntegerField()),
                ('start_timestamp', models.IntegerField()),
                ('is_surprise', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('secret_string', models.CharField(max_length=10)),
                ('mac_add', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.BigIntegerField()),
                ('game_question_id', models.BigIntegerField()),
                ('answer_number', models.IntegerField()),
                ('thinking_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField()),
                ('game_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_question_id', models.BigIntegerField()),
                ('answer_number', models.IntegerField()),
                ('answer_content', models.TextField()),
            ],
        ),
    ]
